# Generated by Django 4.2.7 on 2023-12-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_baja',
        ),
        migrations.AddField(
            model_name='usuario',
            name='baja',
            field=models.BooleanField(default=False, verbose_name='Baja'),
        ),
    ]
