# Generated by Django 4.2.7 on 2023-12-08 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_usuario_fecha_baja_usuario_baja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='baja',
        ),
    ]
